---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/cp -f dist/index.html "$DEPLOYPATH"
    - /bin/find dist -maxdepth 1 -type f \( -name "*.css" -o -name "*.js" \) -exec /bin/cp -f {} "$DEPLOYPATH" \;
    - /bin/cp -Rf dist/assets "$DEPLOYPATH"
    - /bin/sh -c 'if [ -f dist/.htaccess ]; then /bin/cp -f dist/.htaccess "$DEPLOYPATH"; fi'
